### ISSUE TITLE
Should the docs folder be included?

### ISSUE THREAD

**Issue by lukaszmn** [shikaan/titef#34]
Currently, **Titef** occupies 447 kB on disk with 49 files, whereas much richer **Jasmine** takes 524 kB and 108 files. The difference is really small.

I noticed that the distributed package contains the **docs** folder which is hardly useful (or I'm wrong?). Without that folder, Titef would take only 94 kB and 14 files.

What do you think about it?

**Comment by shikaan** [comment]
Hello @lukaszmn :)

Yes, `docs` folder can definitely be taken off of the npm package. 

Actually the sole files really needed are in the `dist` and in the `bin` folder. Isolating them would eventually reduce the size of the package even further.

Do you have a specific use case where the size of the npm package - as opposed to the size of the `js` files - is relevant? 

Thanks for your contribution,
Manuel

**Comment by lukaszmn** [comment]
Haha, for me it's relevant in every project. I am shocked by how simple packages can take megabytes of space and thousands of files. No technical reasons apart from that ;). Thanks

**Comment by shikaan** [comment]
This is solved with latest release: docs are moved to another repo (https://github.com/shikaan/titef-website) and published via Netlify
