### ISSUE TITLE
Types do not include options

### ISSUE THREAD

**Issue by lukaszmn** [shikaan/titef#37]
The types were added in commit [888d93b](https://github.com/shikaan/titef/commit/888d93b08470d031231857a1413d8cf07e856dab). They do not include options as stated in the [doc](https://shikaan.github.io/titef/api/suite/#writing-suites), though.

**Comment by shikaan** [comment]
Hey @lukaszmn,
I have just added a small PR  at #38. Do you want to take a look before the merge?

Thanks again for your contribution

**Comment by lukaszmn** [comment]
Hi, thanks for fixing. I added comment after testing it locally. No problem, take your time :).

**Comment by shikaan** [comment]
Closing because of #38
